[package]
name = "lumina-scripting"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4"] }
log = "0.4"
serde_json.workspace = true
